#!/usr/bin/env bash
#
# Copyright (c) 2016, Thomas Farr
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

job_name=$(uuidgen)
work_dir="$HOME/.abc2png/$job_name"
mkdir -p $work_dir
trap 'rm -rf "$work_dir"' EXIT

cd $work_dir

cat > $job_name.abc

if abcm2ps -S $job_name.abc -O $job_name.ps 2> $job_name.error \
    && convert -density 576 $job_name.ps -append -trim -resize 50% \
               -bordercolor transparent -border 10 $job_name.png 2> $job_name.error ; then
  cat $job_name.png
  exit 0
else
  cat $job_name.error >&2
  exit 1
fi