#!/usr/bin/env python3

"""
Copyright (c) 2016, Thomas Farr

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""


from aiohttp import web
import asyncio
import subprocess


async def latex2png(request):
  proc = await asyncio.create_subprocess_exec(
      'latex2png',
      stdin=subprocess.PIPE,
      stdout=subprocess.PIPE,
      stderr=subprocess.PIPE)

  stdout, stderr = await proc.communicate(input=await request.read())

  if proc.returncode == 0:
    return web.Response(body=stdout, content_type='image/png')
  elif proc.returncode == 124:
    return web.Response(status=408, text='Timed Out')
  else:
    return web.Response(status=400, text=stderr.decode('UTF-8'))


app = web.Application()
app.router.add_route('POST', '/', latex2png)
web.run_app(app)
